### ISSUE TITLE
Card doesn't display correctly on Ubuntu Chrome

### ISSUE THREAD

**Issue by Tyriar** [Tyriar/pathfinding-visualiser#30]
Conflict with styles:

``` css
pv-info-card #container.visible {
visibility: visible;
transition: 0s;
-webkit-transition: 0s;
top: 0em;
}
pv-pathfinding-visualiser #container {
position: absolute;
left: 0px;
right: 0px;
top: 0px;
bottom: 0px;
background-color: rgb(255, 255, 255);
overflow: hidden;
}
```
